### ISSUE TITLE
Potential Bug?

### ISSUE THREAD

**Issue by Xinshi0726** [xujli/MIE-ACL-2020-torch#1]
Epoch 1::   0%|▎                                                                                                     | 1/370 [00:03<23:41,  3.85s/it]
Traceback (most recent call last):
  File "/root/autodl-nas/MIE-ACL-2020-torch/main.py", line 51, in <module>
    model.train(
  File "/root/autodl-nas/MIE-ACL-2020-torch/src/network.py", line 589, in train
    slot_pred_labels, num = self.Dmodels[slot](self.slot_utt_hs_dict[slot], self.slot_candidate_cs_dict[slot],
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/autodl-nas/MIE-ACL-2020-torch/src/network.py", line 188, in forward
    torch.matmul(
RuntimeError: The size of tensor a (35) must match the size of tensor b (1225) at non-singleton dimension 0
root@container-893311b7ac-b1877a90:~/autodl-nas/MIE-ACL-2020-torch# 

When I try to run the code, I got the message above. Could you check that please? Thanks!

**Comment by Xinshi0726** [comment]
I have forked the project and fixed all bugs. If anyone need to use this project, you can find it in my repository.
